"""One-command build of the portable exe (architecture.md §6).

Usage:
    python build.py            # ensure venv, install PyInstaller, build

Output: dist/ARPScanner.exe — single file, no install, no admin, no Npcap.
"""

from __future__ import annotations

import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.abspath(__file__))
VENV = os.path.join(ROOT, ".venv")
VENV_PY = os.path.join(VENV, "Scripts", "python.exe")
DIST_EXE = os.path.join(ROOT, "dist", "ARPScanner.exe")

SPEC = """\
# -*- mode: python ; coding: utf-8 -*-
# Generated by build.py — do not edit by hand.
# Portable GUI build: onefile, windowed, stdlib-only (architecture.md §6).

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['unittest', 'pydoc_data', 'distutils', 'lib2to3'],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='ARPScanner',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
"""


def _run(cmd: list[str]) -> None:
    print("+", " ".join(cmd), flush=True)
    subprocess.run(cmd, check=True, cwd=ROOT)


def ensure_venv() -> None:
    if os.path.isfile(VENV_PY):
        print("[i] venv already present")
        return
    print("[i] creating venv …")
    _run([sys.executable, "-m", "venv", VENV])
    _run([VENV_PY, "-m", "pip", "install", "--quiet", "--upgrade", "pip"])


def ensure_pyinstaller() -> None:
    code = subprocess.run(
        [VENV_PY, "-c", "import PyInstaller"], capture_output=True
    ).returncode
    if code == 0:
        print("[i] PyInstaller already installed")
        return
    print("[i] installing PyInstaller …")
    _run([VENV_PY, "-m", "pip", "install", "--quiet", "pyinstaller"])


def main() -> int:
    ensure_venv()
    ensure_pyinstaller()

    spec_path = os.path.join(ROOT, "ARPScanner.spec")
    with open(spec_path, "w", encoding="utf-8") as fh:
        fh.write(SPEC)
    print("[i] wrote", spec_path)

    _run([VENV_PY, "-m", "PyInstaller", "ARPScanner.spec", "--clean", "--noconfirm"])

    if not os.path.isfile(DIST_EXE):
        print("[!] build finished but exe not found:", DIST_EXE)
        return 1

    size_mb = os.path.getsize(DIST_EXE) / (1024 * 1024)
    print(f"\n[OK] {DIST_EXE}  ({size_mb:.1f} MB)")
    print("Portable: copy anywhere and run — no Python, no Npcap, no admin.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
