"""Headless smoke test: drive the full pipeline with crafted logs and assert
the expected alerts fire (severity, rule, group key).

Run:  python tests/smoke_test.py
"""
from __future__ import annotations

import os
import queue
import sys
import tempfile
import time

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from siem.config import DEFAULT_CONFIG  # noqa: E402
from siem.pipeline import Pipeline  # noqa: E402
from siem.storage import Storage  # noqa: E402

LOGS = [
    # brute force: 6 failed passwords from the same host → 1 high alert
    *["sshd: Failed password for root from 192.168.1.50 port 22 ssh2"] * 6,
    # SQLi → 1 critical alert
    '10.0.0.5 - - [07/Sep/2026:10:01:00 +0000] "GET /products.php?id=1\' OR \'1\'=\'1 HTTP/1.1" 200 1234 "-" "Mozilla/5.0"',
    # 404 flood: 21 hits from the same ip → 1 medium alert
    *[f"10.0.0.5 - - [07/Sep/2026:10:02:{i:02d} +0000] \"GET /x{i}.php HTTP/1.1\" 404 512 \"-\" \"-\"" for i in range(21)],
    # fail-then-success → 1 high alert
    "sshd: Failed password for admin from 10.0.0.9 port 22 ssh2",
    "sshd: Accepted password for admin from 10.0.0.9 port 22 ssh2",
    # privilege escalation → 1 high alert
    "sudo: pam_unix(sudo:auth): authentication failure; logname=alice uid=1000 user=alice",
    # benign lines must NOT alert
    "GET /index.html HTTP/1.1 200 1024",
    "sshd: Accepted publickey for bob from 10.0.0.8 port 22 ssh2",
]


def main() -> int:
    tmp = tempfile.mkdtemp(prefix="siem_smoke_")
    storage = Storage(os.path.join(tmp, "test.db"), max_events_kept=100000)
    cfg = dict(DEFAULT_CONFIG)
    cfg["alert_beep"] = False
    pipeline = Pipeline(storage, cfg)
    pipeline.start()

    alerts: list = []
    pipeline.on_alert = lambda a: alerts.append(a)  # also captured by ui_q in GUI; headless here
    # NOTE: on_alert was wired before start; pipeline uses the callback directly.

    # Wire an echo notifier with an in-memory sink so the outbound path is
    # exercised in the smoke test without touching real network / stdout.
    from siem.notifiers import EchoNotifier
    echo_q: "queue.Queue[str]" = queue.Queue()
    pipeline.attach_notifiers([EchoNotifier({}, sink=echo_q)])
    echo_out: list[str] = []

    n = pipeline.ingest_text("\n".join(LOGS), "smoke")
    # wait for the processor to drain the queue
    deadline = time.time() + 10
    while time.time() < deadline and (pipeline.raw_q.qsize() > 0 or
                                      pipeline.stats["processed"] < n):
        time.sleep(0.1)

    time.sleep(0.5)  # let alert callbacks + notifiers land
    pipeline.stop()

    while not echo_q.empty():
        try:
            echo_out.append(echo_q.get_nowait())
        except queue.Empty:
            break

    by_rule = {}
    for a in alerts:
        by_rule.setdefault(a.rule_id, []).append(a)

    # Notifier assertion: every alert generated by the smoke logs should have
    # produced one echo notifier line containing its rule_id.
    echo_contains_rules = {
        rid: any(rid in line for line in echo_out)
        for rid in by_rule
        if by_rule[rid]
    }

    by_rule = {}
    for a in alerts:
        by_rule.setdefault(a.rule_id, []).append(a)

    checks = [
        ("rule_brute_force", 1, "high", "possible brute force"),
        ("rule_sqli", 1, "critical", "sql injection"),
        ("rule_many_404", 1, "medium", "many 404s"),
        ("rule_seq_fail_success", 1, "high", "fail-then-success"),
        ("rule_priv_esc", 1, "high", "privilege escalation"),
    ]
    ok = True
    for rule_id, expect_count, expect_sev, label in checks:
        got = by_rule.get(rule_id, [])
        status = "PASS" if len(got) == expect_count and got and got[0].severity == expect_sev else "FAIL"
        if status == "FAIL":
            ok = False
        print(f"[{status}] {label:28s} rule={rule_id} alerts={len(got)} "
              f"sev={got[0].severity if got else '-'} (expected {expect_count}x {expect_sev})")

    # dedup check: alert count for brute force must be exactly 1 despite 6 matches
    no_false = len(by_rule.get("rule_error_spike", [])) == 0
    print(f"[{'PASS' if no_false else 'FAIL'}] benign lines produced no alerts")
    ok = ok and no_false

    echo_ok = all(echo_contains_rules.values()) and len(echo_out) >= len(alerts)
    print(f"[{'PASS' if echo_ok else 'FAIL'}] notifiers: {len(echo_out)} echo lines for {len(alerts)} alerts")
    ok = ok and echo_ok

    stored = storage.get_alerts(50)
    print(f"\nstored alerts in DB: {len(stored)}; processed={pipeline.stats['processed']} "
          f"normalized={pipeline.stats['normalized']} dropped={pipeline.stats['dropped']}")
    for a in stored[:5]:
        print(f"  #{a.id} {a.display_time()} [{a.severity}] {a.rule_name} — {a.summary}")
    storage.close()
    print("\nRESULT:", "ALL PASS" if ok else "FAILURES PRESENT")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())